name: 'f1_dbt'
version: '1.0.0'
profile: 'f1_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  f1_dbt:

    # Experimental models (not built by default)
    experiments:
      +enabled: false
      +tags: ["experimental"]

    # Staging layer (raw → cleaned)
    staging:
      +materialized: view
      +schema: staging
      +tags: ["staging"]

    # Mart layer (business-ready models)
    marts:
      +materialized: table
      +schema: analytics
      +tags: ["mart", "analytics"]