name: 'f1_dbt'
version: '1.0.0'
profile: 'f1_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  f1_dbt:
    # Staging models are lightweight views over raw tables
    staging:
      +materialized: view
      +schema: staging

    # Mart models are analytics-ready tables (dimensions & facts)
    marts:
      +materialized: table
      +schema: analytics