version: 2

models:
  - name: fact_results
    description: "Race results fact table"
    columns:
      - name: race_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_races')
                field: race_id

      - name: driver_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_drivers')
                field: driver_id

      - name: constructor_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_constructors')
                field: constructor_id