version: "3.9"

services:
  postgres:
    image: postgres:18
    container_name: f1_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      # IMPORTANT: mount one level higher for Postgres 18+
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: