version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: f1_postgres
    restart: always
    environment:
      POSTGRES_USER: f1_user
      POSTGRES_PASSWORD: f1_password
      POSTGRES_DB: f1_raw
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: