version: 2

sources:
  - name: f1_raw
    description: "Raw Formula 1 data ingested from Ergast API"
    schema: public
    tables:
      - name: drivers_raw
      - name: constructors_raw
      - name: races_raw
      - name: results_raw